DonationPage/DonationPage/Controllers/DonationEntriesController.cs
using System;
using System.Configuration;
using System.Data;
using System.Globalization;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web.Mvc;
using DonationPage.Models;

namespace DonationPage.Controllers
{
    public class DonationEntriesController : Controller
    {
        // private DonationPageContext db = new DonationPageContext();
        private TableManager<DonationEntry> tableManager = new TableManager<DonationEntry>("donationconfirmation");
        private const string PartitionKey = "donation-confirmation";

        // GET: DonationEntries
        public async Task<ActionResult> Index()
        {
            ViewBag.Title = "Donation stories to approve";

            var allItems = await tableManager.GetAllEntitiesAsync();
            return View(allItems.Where(x => !x.Approved).ToList());
        }

        // GET: DonationEntries/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            DonationEntry donationEntry = tableManager.GetEntity(PartitionKey, id);

            if (donationEntry == null)
            {
                return HttpNotFound();
            }
            return View(donationEntry);
        }

        // GET: DonationEntries/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: DonationEntries/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "DonationID,Honoree,Comments")] DonationEntry donationEntry)
        {
            if (ModelState.IsValid)
            {
                donationEntry.PartitionKey = PartitionKey;
                donationEntry.RowKey = donationEntry.DonationID;
                donationEntry.Approved = true;

                await tableManager.CreateEntityAsync(donationEntry);

                return RedirectToAction("Index");
            }

            return View(donationEntry);
        }

        public async Task<ActionResult> Stories()
        {
            var allItems = await tableManager.GetAllEntitiesAsync();
            return View(allItems.Where(x => x.Approved).ToList());
        }

        public async Task<ActionResult> FullList()
        {
            ViewBag.Title = "All stories";

            var allItems = await tableManager.GetAllEntitiesAsync();
            return View("Index", allItems);
        }

        // GET: DonationEntries/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DonationEntry donationEntry = tableManager.GetEntity(PartitionKey, id);
            if (donationEntry == null)
            {
                return HttpNotFound();
            }
            return View(donationEntry);
        }

        // POST: DonationEntries/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(DonationEntry donationEntry)
        {
            if (ModelState.IsValid)
            {
                tableManager.UpsertEntity(donationEntry);
                return RedirectToAction("Index");
            }
            return View(donationEntry);
        }

        // GET: DonationEntries/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DonationEntry donationEntry = tableManager.GetEntity(PartitionKey, id);
            if (donationEntry == null)
            {
                return HttpNotFound();
            }
            return View(donationEntry);
        }

        // POST: DonationEntries/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            DonationEntry donationEntry = tableManager.GetEntity(PartitionKey, id);
            tableManager.DeleteEntity(donationEntry);

            return RedirectToAction("Index");
        }

        public ActionResult Settings()
        {
            ViewBag.Title = "Settings";
            return View("Settings");
        }

        [HttpPost, ActionName("SetupWehbook")]
        public async Task<ActionResult> SetupWehbook()
        {
            using (var client = new HttpClient())
            using (var response = await client.GetAsync(ConfigurationManager.AppSettings["RegisterWebhookEndpoint"]))
            {
                if (response.IsSuccessStatusCode)
                {
                    return Json(new { data = await response.Content.ReadAsStringAsync() });
                }
                else
                {
                    throw new InvalidOperationException(string.Format(CultureInfo.InvariantCulture, "{0} {1}", response.StatusCode, await response.Content.ReadAsStringAsync()));
                }
            }
        }

        [HttpPost, ActionName("RemoveWehbook")]
        public async Task<ActionResult> RemoveWehbook()
        {
            using (var client = new HttpClient())
            using (var response = await client.GetAsync(ConfigurationManager.AppSettings["RemoveWebhookEndpoint"]))
            {
                if (response.IsSuccessStatusCode)
                {
                    return Json(new { data = await response.Content.ReadAsStringAsync() });
                }
                else
                {
                    throw new InvalidOperationException(string.Format(CultureInfo.InvariantCulture, "{0} {1}", response.StatusCode, await response.Content.ReadAsStringAsync()));
                }
            }
        }

        [HttpPost, ActionName("GetWehbook")]
        public async Task<ActionResult> GetWehbook()
        {
            using (var client = new HttpClient())
            using (var response = await client.GetAsync(ConfigurationManager.AppSettings["GetWebhookEndpoint"]))
            {
                if (response.IsSuccessStatusCode)
                {
                    return Json(new { data = await response.Content.ReadAsStringAsync() });
                }
                else
                {
                    throw new InvalidOperationException(string.Format(CultureInfo.InvariantCulture, "{0} {1}", response.StatusCode, await response.Content.ReadAsStringAsync()));
                }
            }
        }
    }
}

DonationPage/DonationPage/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Montserrat">
</head>
<body>

    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("LadyBugHouseAdmin", "Index", "DonationEntries", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav" style="float: left">
                    <li>@Html.ActionLink("Approved stories", "Stories", "DonationEntries")</li>
                    <li>@Html.ActionLink("All stories", "FullList", "DonationEntries")</li>
                    <li>@Html.ActionLink("Settings", "Settings", "DonationEntries")</li>
                    <li>
                        <a href="http://www.ladybughouse.org/" target="_blank">LadyBugHouseOrg</a>
                    </li>
                </ul>
                <img src="~/Content/Images/titleWithLogo.png" style="float: right; width :20%; padding-top: 5px" />
                <ul style="clear: both"></ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>